= Cheatsheet - Matrices
Fabio Lama <fabio.lama@pm.me>
:description: Module: CM1015 Computational Mathematics, started 04. April 2022
:doctype: article
:sectnums: 4
:toclevels: 4
:stem:

== Intro

A **matrix** is a set of numbers ("elements") arranged in the form of a
rectangle and enclosed in curved brackets. The matrix _A_ is of size **"two by
three"**:

[stem]
++++
A = ([1,2,3],[3,4,6])
++++

A **square** matrix has the same number of rows as colummns:

[stem]
++++
([2,-7],[-1,6])
++++

A **diagnoal** matrix is a square matrix where all elements are _0_ except those
on the diagonal from the top left to the bottom right.

[stem]
++++
([7,0],[0,9]) " , " ([9,0],[0,0]) " and " ([-1,0,0],[0,8,0],[0,0,-17])
++++

An **identity** matrix is a diagonal matrix where all the diagonal elements are equal to _1_.

== Addition and Subtraction

Two matrices that have the same size can be added/subtracted by simply
adding/subtracting the corresponding elements:

[stem]
++++
([1,2],[3,4]) + ([5,2],[1,0]) = ([1+5, 2+2],[3+1,4+0]) = ([6,4],[4,4])
++++

Respectively:

[stem]
++++
([1,2],[3,4]) + ([5,2],[1,0]) = ([1-5, 2-2],[3-1,4-0]) = ([-4,0],[2,4])
++++

== Multiplication and Division by Number

A matrix is multiplied by a number by multiplying/dividing each element by that
number:

[stem]
++++
4([1,2],[3,-9]) = ([4 xx 1, 4 xx 2],[4 xx 3, 4 xx -9]) = ([4,8],[12,-36])
++++

Respectively:

[stem]
++++
1/4([16],[8]) = ([1/4 xx 16],[1/4 xx 8]) = ([4],[2])
++++
