= Cheatsheet - Probability
Fabio Lama <fabio.lama@pm.me>
:description: Module: CM1015 Computational Mathematics, started 04. April 2022
:doctype: article
:sectnums: 4
:toclevels: 4
:stem:

== Intro

Some events are impossible, while others are quite certain to happen. When
something is impossible, we say that the probability is **0**. If something is
very likely going to happen, we say the probability is **1**. We use the letter
**P** to indicate a probability of something occuring.

[stem]
++++
P("a human will live for 1'000 years") = 0\
P("all of us will die someday") = 1
++++

No probabilities are outside the range of 0 to 1.

We say that two events are **complementary** if they exclude each other, for
example something can either exist or not exist, but not exist and not exist at
the same time. The sum of the probabilities of the two complementary events must
always equal 1, also known as the **total probability**.

== Calculating Theoretical Probabilities

If the odds of some event occuring is the same for all possible events (e.g.
when rolling a dice), the probability is **unbiased**. This **theoretical
probability** is calculated the following way:

[stem]
++++
P("obtaining our chosen event") = ("number of ways the chosen event can occur"/"total number of possibilities")
++++

For example, the probability of rolling _4_ on a dice is:

[stem]
++++
P("rolling 4") = 1/6 = 0.1666...
++++

Or, the probability of rolling above _4_ (by rolling _5_ or _6_):

[stem]
++++
P("rolling above 4") = 2/6 = 1/3 = 0.333...
++++

== Independent Events

If two events such as stem:[A] and stem:[B] are **independent** from each other,
then the probability of obtaining stem:[A] and stem:[B] is given by:

[stem]
++++
P(A " and " B) = P(A) xx P(B)
++++

For example, what is the probability that a coin toss and a dice throw result in
a _head_ and a _six_? We calculate:

[stem]
++++
1/2 xx 1/6 = 1/12
++++

== Combinatorics

We can calculate the permutations and combinations of elements. Permutations and
combinations are similar, but differ due to the fact that combinations do not
care about ordering.

=== Permutations

A **permutations** of _n_ different elements is an ordering of the elements such
that one element is first, one is second, one is third, and so on. In order to
calculate the number of different permutations of _n_ elements we use the
**factorial** of _n_, respectively stem:[n!]:

[stem]
++++
n! = n xx (n-1) xx ... 2 xx 1
++++

For example:

[stem]
++++
6! = 1 xx 2 xx 3 xx 4 xx 5 xx 6 = 720
++++

Additionally, there are stem:[3! = 6] permutations of the letters stem:[X, Y]
and stem:[Z]:

[stem]
++++
X Y Z\
Y X Z\
X Z Y\
Z Y X\
Z X Y\
Y Z X
++++

NOTE: stem:[0! = 1].

==== Permutations of stem:[n] Elements Taken stem:[r] at the Time

The number of permutations of _n_ elements taken _r_ at a time:

[stem]
++++
P_r^n = (n!)/(n-r)! = n(n -1)(n-2)...(n-r+1)
++++

For example, consider the question:

> There are 8 horses running in a race. In how many different ways can these
horses come in first, second and thrid (ties excluded)?

We can calculate:

[stem]
++++
P_3^8 = (8!)/((8-3)!) = (8!)/(5!) = 336
++++

==== Distinguishable Permutations

TODO

=== Combinations

Unlike permutations, combinations do not care about ordering. Respectively:

[stem]
++++
{A, B, C} = {C, B, A}
++++

To calculate the number of possible combinations of stem:[{A, B, C}], we use the
number of letters as stem:[r] and use the following formula (where stem:[P_r^n]
is defined in the permutations section):

[stem]
++++
C_r^n = (n!)/((n-r)!r!) = (P_r^n)/(r!)
++++

respectively (note that stem:[0! = 1]):

[stem]
++++
C_3^3 = (3!)/((3-3)!3!) = 6/6 = 1
++++

Unlike permutations, combinations always require an stem:[r] (i.e. combinations
of _n_ elements taken at _r_ at a time).
