= Cheatsheet - Statistics
Fabio Lama <fabio.lama@pm.me>
:description: Module: CM1015 Computational Mathematics, started 04. April 2022
:doctype: article
:sectnums: 4
:toclevels: 4
:stem:

== The Arithmetic Mean

The **arithmetic mean**, or **mean**, is the first average and is found in a set
of values by adding up all the values and dividing the result by the total
number of values in the set.

[stem]
++++
"mean" = ("sum of the values")/("total number of values")
++++

For example, the sum of all marks is stem:[5 + 8 + 8 + 6 = 27], where the number
of marks is stem:[4], hence:

[stem]
++++
27/4 = 6.75
++++

In more advanced math, we say we have stem:[n] values and call those stem:[x_1,
x_2, ..., x_n] where the _mean_ is given as stem:[bar x] ("x bar"). We sum up
all those values and divide it by _n_:

[stem]
++++
bar x = (sum_(i = 1)^n x_i)/n
++++

=== Frequencies

When the data is presented in the form of a frequency distribution the mean is
found by first multiplying each data value by its frequency and the mean is
found by dividing this sum by the sum of all the frequencies

The frequencies are given as:

[stem]
++++
f_1 -> x_1\
f_2 -> x_2\
f_3 -> x_3\
...\
f_n -> x_n
++++

For example, a frequency distribution would be a table that shows how  many
students (stem:[f_n]) got which mark (stem:[x_n]):

[stem]
++++
0 -> 0 " (0 students got mark 0)"\
...\
15 -> 7 " (15 students got mark 7)"\
12 -> 8 " (12 students got mark 8)"\
...
++++

And is calculated as:

[stem]
++++
bar x = (sum_(i=1)^n f_i xx x_i)/(sum_(i=1)^n f_i)
++++

== The Median

The **median** is the second average and is found in a set a set of values by
listing the numbers in ascending order and the selecting the value that lies
halfway along the list. If there are two numbers halfway, implying the size of
the set is even, then the two numbers are averages (i.e. the mean).

For example, in the set stem:[{1,4,5,7,9}] the value haflway is stem:[5], making
that value the **median** of the set. Additionally, in the set
stem:[{3,4,5,6,7,7}] there are two values halfway, stem:[5] and stem:[6], and we
can calculate the mean in order to receive the median:

[stem]
++++
(5+6)/2 = 11/2 = 5.5
++++

== The mode

The **mode** is the third average and indicates in a set of values what value
occurs the most often. For example, in the set of values stem:[{1, 2, 3, 4, 4,
4, 5, 5}] the value stem:[4] appears the most, making it the mode. Sets that
have two modes are called **bimodal**.

== Variance and Standard Deviation

The means of sets be the same even though the values are widely spread, for
example:

[stem]
++++
4 + 7 + 10 = 7\
7 + 7 + 7 = 7
++++

If this spread/information should be considered, then the **variance** and
**standard deviation** is used.

=== Variance

The variance shows the spread between the values.

[stem]
++++
"variance" = (sum_(i=1)^n (x_i - bar x)^2)/n
++++

Respectively:

[stem]
++++
"variance" = ((4 - 7)^2 + (7 - 7)^2 + (10 - 7)^2)/3 = 18/3 = 6
++++

and

[stem]
++++
"variance" = ((7 - 7)^2 + (7 - 7)^2 + (7 - 7)^2)/3 = 0
++++

Even though the mean between the two sets are the same, the variance shows us
that the spread differs quite a lot between both sets.

In case of frequency distribution:

[stem]
++++
"variance" = (sum_(i=1)^n f_i (x_i - bar x)^2)/(sum_(i=1)^n f_i)
++++

=== Standard Deviation

The standard deviation shows the deviation from the mean, indicating which
values are "standard", and which values are "non-standard" respectively vary a
lot from most values.

[stem]
++++
"standard deviation" = sqrt ((sum_(i=1)^n (x_i - bar x)^2)/n)
++++

The standard deviation is just the square root of the variance. From the
examples in the variance section, we can conclude:

[stem]
++++
"standard deviation" = sqrt (6) ~~ 2.449
++++

and

[stem]
++++
"standard deviation" = sqrt (0)\ = 0
++++

Any values above (stem:[bar x + "standard deviation"]) and below (stem:[bar x -
"standard deviation"]) the mean are considered non-standard.
