= Cheatsheet - Statistics
Fabio Lama <fabio.lama@pm.me>
:description: Module: CM1015 Computational Mathematics, started 04. April 2022
:doctype: article
:sectnums: 4
:toclevels: 4
:stem:

== The Arithmetic Mean

The **arithmetic mean**, or **mean**, is the set of values found by adding up
all the values and dividing the result by the total number of values in the set.

[stem]
++++
"mean" = ("sum of the values")/("total number of values")
++++

For example, the sum of all marks is stem:[5 + 8 + 8 + 6 = 27], where the number
of marks is stem:[4], hence:

[stem]
++++
6.75 = 27/4
++++

In more advanced math, we say we have stem:[n] values and call those stem:[x_1,
x_2, ..., x_n] where the _mean_ is given as stem:[bar x] ("x bar"). We sum up
all those values and divide it by _n_:

[stem]
++++
bar x = (sum_(i = 1)^n x_i)/n
++++

=== Frequencies

When the data is presented in the form of a frequency distribution the mean is
found by first multiplying each data value by its frequency and the mean is
found by dividing this sum by the sum of all the frequencies

The frequencies are given as:

[stem]
++++
f_1 -> x_1\
f_2 -> x_2\
f_3 -> x_3\
...\
f_n -> x_n
++++

For example, a frequency distribution would be a table that shows how  many
students (stem:[f_n]) got which mark (stem:[x_n]):

[stem]
++++
0 -> 0 " (0 students got mark 0)"\
...\
15 -> 7 " (15 students got mark 7)"\
12 -> 8 " (12 students got mark 8)"\
...
++++

And is calculated as:

[stem]
++++
bar x = (sum_(i=1)^n f_i xx x_i)/(sum_(i=1)^n f_i)
++++

== The mode

A third average is the **mode**, which indicates in a set of values what value
occurs the most often. For example, in the set of values stem:[{1, 2, 3, 4, 4,
4, 5, 5}] the value stem:[4] appears the most, making it the mode. Sets that
have two modes are called **bimodal**.

== Variance and Standard Deviation

The means of sets be the same even though the values are widely spread, for
example:

[stem]
++++
4 + 7 + 10 = 7\
7 + 7 + 7 = 7
++++

If this spread/information should be considered, then the **variance** and
**standard deviation** is used.

[stem]
++++
"variance" = (sum_(i=1)^n (x_i - bar x)^2)/n
++++

In case of frequency distribution:

[stem]
++++
"variance" = (sum_(i=1)^n f_i (x_i - bar x)^2)/(sum_(i=1)^n f_i)
++++

[stem]
++++
"standard deviation" = sqrt ((sum_(i=1)^n (x_i - bar x)^2)/n)
++++

TODO...
