= Graphs and Functions
Fabio Lama <fabio.lama@pm.me>
:description: Module: CM1015 Computational Mathematics, started 04. April 2022
:doctype: book
:toc:
:sectnums: 4
:toclevels: 4
:stem:

== Intro

We introduce horizontal and vertical axes. These axes intersect at a point
stem:[O] called the origin. The horizontal axis is used to represent the
independent variable, commonly stem:[x], and the vertical axis is used to
represent the dependent variable, commonly stem:[y]. The region shown is then
referred to as the stem:[x – y] plane.

== Inequalities

Adding and subtracting the same quantity from both sides of an inequality leaves
the inequality unchanged. Hence, for any quantity stem:[k] if:

[stem]
++++
x > y
++++

then:

[stem]
++++
x + k > y + k " and " x -k > y -k
++++

Multiplying and dividing *positive* quantity then the inequality remains
*unchanged*. If stem:[x > y] and stem:[k] is positive, then:

[stem]
++++
kx > ky " and " x/k > y/k
++++

Multiplying and dividing *negative* quantity then the inequality is *reversed*. 
If stem:[x > y] and stem:[k] is negative, then:

[stem]
++++
kx < ky " and " x/k < y/k
++++

== Intervals

