= Sequences and Series
Fabio Lama <fabio.lama@pm.me>
:description: Module: CM1015 Computational Mathematics, started 04. April 2022
:doctype: book
:toc:
:sectnums: 4
:toclevels: 4
:stem:

== Intro

**Sequence**: A set of (arbitrary) numbers ("terms") written down in a specific order.

[stem]
++++
S = (1, 3, 5, 7, 9)
++++

A sequence can be _finite_ or _infinite_:

[stem]
++++
S = (0, 1, 2, 3, ...)
++++

== Notations

Given stem:[S = (0, 1, 2, 3)], then stem:[S_2 in S] equals to stem:[1] and
stem:[S_3 in S] equals to stem:[2] (sometimes the index starts at _0_, common in Computer Science).

Terms of a sequence can often be found by using a formula. For example, given:

[stem]
++++
x_k = 2k + 3
++++

then stem:[x_3 = 2 xx 3 + 3 = 9] and stem:[x_4 = 11].

== Arithmetic Progression

A arithmetic progression (or sequence) _adds_ a fixed amount to the previous
term.

[stem]
++++
S = (a, a + d, a + 2d, a + 3d, ...)
++++

where stem:[a] is the _first term_ and stem:[d] is the _commond difference_ of
the arithmetic progression stem:[S]. For example:

[stem]
++++
S = (1, 7, 13, 19, ...)
++++

where stem:[a in S] is _1_ and stem:[d in S] is _6_. The stem:[n]-th term of an
arithmetic progression is given by:

[stem]
++++
a + (n-1)d
++++

For example, the third term in stem:[S] is:

[stem]
++++
S_3 = 1 + (3 -1)6\
S_3 = 1 + 2 xx 6\
S_3 = 13
++++

== Geometric Progression

A geometric progression (or sequence) _multiplies_ the previous terms by a fixed
amount.

[stem]
++++
S = (a,ar,ar^2,ar^3,...)
++++

where stem:[a] is the _first term_ and stem:[r] is the _common ratio_. For exampe:

[stem]
++++
S = (2, 10, 50, 250, ...)
++++

where stem:[a in S] is _2_ and stem:[r in S] is _5_. The stem:[n]-th term of an
geometric progression is given by:

[stem]
++++
ar^(n-1)
++++

For example, the third term in stem:[S] is:

[stem]
++++
S_3 = 2 xx 5^(3-1)\
S_3 = 2 xx 5^2\
S_3 = 50
++++

== Infinite Sequences

An infinite sequences continues indefinitely. As the sequences progresses, it
gets closer and closer to a fixed value. For example, the following sequences
and smaller

[stem]
++++
S = (s, 1/2, 1/3/, 1/4, 1/5, ...)
++++

which can be written as stem:[x_k = 1/k] for stem:[k = (1, 2, 3, ...)]. We say that "stem:[1/k] tends to zero as stem:[k] tends to infinity" or "as stem:[k] tends to infinity, the _limit_ of the sequence is zero":

[stem]
++++
lim_(k -> oo) 1/k = 0
++++

When a sequence possesses a limit it is said to **converge**. A sequence such as
stem:[x_k = 3k - 2] which is stem:[(1, 4, 7, 10, ...)] does have a limit, which
is said to **diverge**.

== Series & Sigma Notation

If the terms of a sequence are added, the result is known as a _series_.

[stem]
++++
sum_(k=1)^(k=5) k = 1 + 2 + 3 + 4 + 5 = 15
++++

Note that notations can be abbreviated:

[stem]
++++
sum_(k=1)^(k=5) k = sum_(k = 1)^5 k = sum_1^5 k
++++

== Arithmetic Series

If the terms of an arithmetic sequence are added, the result is known as an arithmetic series. The sum of the first stem:[n] terms of an arithmetic series with first term stem:[a] and common difference stem:[d] is denoted by stem:[S_n] and given by:

[stem]
++++
S_n = n/2 (2a + (n-1)d)
++++

For example, the sum of the first stem:[3] terms of stem:[sum_(k=1)^(k=5) k] is:

[stem]
++++
S_3 = 3/2 (2 xx 1 + (3 -1)1)\
S_3 = 3/2 xx 4/1\
S_3 = 12/2 = 6/1 = 6
++++

== Geometric Series

If the terms of a geometric sequence are added, the result is known as a
geometric series. The sum of the first stem:[n] terms of a geometric series with
first term stem:[a] and common ratio stem:[r] is denoted by stem:[S_n] and given
by:

[stem]
++++
S_n = (a(1-r^n))/(1-r) " provided " r " is not equal to " 1
++++

For example, the sum of the stem:[3] first terms of stem:[(2, 10, 50, 250, ..)] is:

[stem]
++++
S_3 = (2(1-5^3))/(1-5)\
S_3 = (2xx1-2xx5^3)/(-4)\
S_3 = (-248)/-4 = 62
++++

== Infinite Geometric Series

If the terms of an infite sequence are added, the result is known as an infinite
series. The sum of an infite number of terms of a geometric series with first term
stem:[a] and common ratio stem:[r] is denoted by stem:[S_(oo)] and given by:

[stem]
++++
S_(oo) = a/(1-r) " provided " -1 < r < 1
++++

For example, a first term of stem:[2] and a common ration of stem:[1/3] is:

[stem]
++++
S_(oo) = 2/(1-(1/3)) = 2/(2/3) = 3
++++
