= Sequences and Series
Fabio Lama <fabio.lama@pm.me>
:description: Module: CM1015 Computational Mathematics, started 04. April 2022
:doctype: book
:toc:
:sectnums: 4
:toclevels: 4
:stem:

== Intro

**Sequence**: A set of (arbitrary) numbers ("terms") written down in a specific order.

[stem]
++++
S = (1, 3, 5, 7, 9)
++++

A sequence can be _finite_ or _infinite_:

[stem]
++++
S = (0, 1, 2, 3, ...)
++++

== Notations

Given stem:[S = (0, 1, 2, 3)], then stem:[S_2 in S] equals to stem:[1] and
stem:[S_3 in S] equals to stem:[2] (sometimes the index starts at _0_, common in Computer Science).

Terms of a sequence can often be found by using a formula. For example, given:

[stem]
++++
x_k = 2k + 3
++++

then stem:[x_3 = 2 xx 3 + 3 = 9] and stem:[x_4 = 11].

== Arithmetic Progression

A arithmetic progression (or sequence) _adds_ a fixed amount to the previous
term.

[stem]
++++
S = (a, a + d, a + 2d, a + 3d, ...)
++++

where stem:[a] is the _first term_ and stem:[d] is the _commond difference_ of
the arithmetic progression stem:[S]. For example:

[stem]
++++
S = (1, 7, 13, 19, ...)
++++

where stem:[a in S] is _1_ and stem:[d in S] is _6_. The stem:[n]-th term of an
arithmetic progression is given by:

[stem]
++++
a + (n-1)d
++++

For example, the third term in stem:[S] is:

[stem]
++++
S_3 = 1 + (3 -1)6\
S_3 = 1 + 2 xx 6\
S_3 = 13
++++

== Geometric Progression

A geometric progression (or sequence) _multiplies_ the previous terms by a fixed
amount.

[stem]
++++
S = (a,ar,ar^2,ar^3,...)
++++

where stem:[a] is the _first term_ and stem:[r] is the _common ratio_. For exampe:

[stem]
++++
S = (2, 10, 50, 250, ...)
++++

where stem:[a in S] is _2_ and stem:[r in S] is _5_. The stem:[n]-th term of an
geometric progression is given by:

[stem]
++++
ar^(n-1)
++++

For example, the third term in stem:[S] is:

[stem]
++++
S_3 = 2 xx 5^(3-1)\
S_3 = 2 xx 5^2\
S_3 = 50
++++

== Infinite Sequences

An infinite sequences continues indefinitely. As the sequences progresses, it
gets closer and closer to a fixed value. For example, the following sequences
and smaller

[stem]
++++
S = (s, 1/2, 1/3/, 1/4, 1/5, ...)
++++

which can be written as stem:[x_k = 1/k] for stem:[k = (1, 2, 3, ...)]. We say that "stem:[1/k] tends to zero as stem:[k] tends to infinity" or "as stem:[k] tends to infinity, the _limit_ of the sequence is zero":

[stem]
++++
lim_(k -> oo) 1/k = 0
++++

When a sequence possesses a limit it is said to **converge**. A sequence such as
stem:[x_k = 3k - 2] which is stem:[(1, 4, 7, 10, ...)] does have a limit, which
is said to **diverge**.

== Series & Sigma Notation

If the terms of a sequence are added, the result is known as a _series_.

[stem]
++++
sum_(k=1)^(k=5) k = 1 + 2 + 3 + 4 + 5 = 15
++++

Note that notations can be abbreviated:

[stem]
++++
sum_(k=1)^(k=5) k = sum_(k = 1)^5 k = sum_1^5 k
++++

== Arithmetic Series

If the terms of an arithmetic sequence are added, the result is known as an arithmetic series. The sum of the first stem:[n] terms of an arithmetic series with first term stem:[a] and common difference stem:[d] is denoted by stem:[S_n] and given by:

[stem]
++++
S_n = n/2 (2a + (n-1)d)
++++

For example, the sum of the first stem:[3] terms of stem:[sum_(k=1)^(k=5) k] is:

[stem]
++++
S_3 = 3/2 (2 xx 1 + (3 -1)1)\
S_3 = 3/2 xx 4/1\
S_3 = 12/2 = 6/1 = 6
++++

**Series**: A sequence derived from another sequence.

[stem]
++++
{a_n} " with " n = {0, 1, 2, ...}\
= {a_0, a_0+a_1,a_0+a_1+a_2,a_0+a_1+a_2+a_3, ...}
++++

* stem:[{s_n}] is called a series, it is a type of sequence that is obtained as
sum of the elements of another sequence.

* A series is also indicated with stem:[sum -> s_n = sum_(i=0)^n a_i]

*(intermezzo) Mathematical induction principle*: if a property is valid for
stem:[n=0], and if, _assuming it is valid for stem:[n], it remains valid also
for stem:[n+1]_, then the property is valid for any stem:[n].

[stem]
++++
s_n = sum_(k=0)^n (a_0+k xx q) = (n+1)(2 a_0 + n xx q) div 2 (x)
++++

prove stem:[x] is true for stem:[n=0], then prove that stem:[s_(n+1) =
s_n+a_(n+1) = (x) + a_0 xx q^(n+1)]
