= Cheatsheet - First-Order Logic
Fabio Lama <fabio.lama@pm.me>
:description: Module: CM1025 Fundamentals to Computer Science, started 25. October 2022
:doctype: article
:sectnums: 4
:stem:

== Predicates

**Predicates** describe properties of objects.

For example:

[stem]
++++
"odd"(3)
++++

stem:["odd"(3)] means stem:[3] is an odd number. stem:["odd"] is a predicate,
stem:[3] is an object. Predicates take arguments and become **propositions**.

Connectives can be applied:

[stem]
++++
"odd"(3) ^^ "prime"(3)
++++

This means that stem:[3] is odd but also prime.

== Quantifiers

We use the symbol stem:[EE] to indicate the existence of something
(**existential quantifier**).

[stem]
++++
EE x " odd"(x)
++++

This means that there exists some stem:[x] that is odd.

We denote the **universal quantifier** as stem:[AA].

[stem]
++++
AA x  ("odd"(x) vv "even"(x))
++++

This meant that **for all** stem:[x] the number is either even or odd.

Other examples, "All Ps are Qs":

[stem]
++++
AA x (P(x) -> Q(x))
++++

And "No Ps are Qs":

[stem]
++++
AA x (P(x) -> not Q(x))
++++

== Quantifiers to Connectives

stem:[EE x, P(x)] where stem:[x in {x_1, x_2, ..., x_n}] means that there exists
some stem:[x] for which stem:[P(x)] is true.

Denoted alternatively:

[stem]
++++
EE x, P(x) -= P(x_1) vv P(x_2) vv ... vv P(x_3)
++++

We can also conclude:

[stem]
++++
not EE x, P(x) -= not(P(x_1) vv P(x_2) vv ... vv P(x_3))\
not EE x, P(x) -= not P(x_1) ^^ not P(x_2) ^^ ... ^^ not P(x_3)\
not EE x, P(x) -= AA x, not P(x)
++++
