= Cheatsheet - Formal Languages
Fabio Lama <fabio.lama@pm.me>
:description: Module: CM1025 Fundamentals to Computer Science, started 25. October 2022
:doctype: article
:sectnums: 4
:stem:

== Regular Operations

Let stem:[L_1] and stem:[L_2] be languages. The following operations are regular operations:

* Union: stem:[L_1 uu L_2 = {x|x in L_1 " or " x in L_2}]
* Concatenation: stem:[L_1 @ L_2 = {xy|x in L_1 " and " y in L_2}]
* Star: stem:[L_1^** = {x_1 x_2 ... x_m | m >= 0, "each " x_1 in L_1}]

For example:

[stem]
++++
A = {a, b, c}\
B = {x, y, z}\
A uu B = {a, b, c, x, y, z}\
A @ B = {ax, ay, az, bx, by, bz, cx, cy, cz}\
A^** = {epsilon, a, b, c, aa, ab, ac, ba, b b, bc, ca, ...}
++++

Where stem:[epsilon] means "none".

=== Properties

==== Union

[stem]
++++
A uu B = B uu A " (commutative)"\
(A uu B) uu C = A uu (B uu C) " (associative)"\
A uu O/ = A\
A uu A = A " (idempotent)"
++++

==== Concatenation

[stem]
++++
(A @ B) @ C = A @ (B @ C) " (associative)"\
A @ epsilon = epsilon @ A = A\
A @ O/ = O/
++++

_Note that concatenation is not commutative_.

==== Concatenation and Union

[stem]
++++
(A uu B) @ C = (A @ C) uu (B @ C)\
A @ (B uu C) = (A @ B) uu (A @ C)
++++

==== Kleene Star

[stem]
++++
O/^** = {epsilon}\
epsilon^** = epsilon\
(A^**)^** = A^**\
A^** @ A^** = A^**\
(A uu B)^** = (A^** B^**)^**
++++

== Regular Expressions

=== Atomic Expressions

The empty language, stem:[O/], is a regular expression, which is the empty
regular language. Any letter stem:[a in Sigma] is a regular expression and its
language is stem:[{a}]. Empty string, stem:[epsilon], is a regular expression
representing the regular language stem:[{epsilon}].

* _Concatenation_: if stem:[R_1] and stem:[R_2] are regular expressions, so is stem:[R_1 @ R_2].
* _Union_: if stem:[R_1] and stem:[R_2] are regular expressions, so is stem:[R_1 uu R_2].
* _Kleene star_: if stem:[R] is a regular expression, so is stem:[R^**].

==== Examples

What is the language of stem:[ab^**]?

[stem]
++++
{a, ab, a b b, ab b b, ...}
++++

What is the language of stem:[ab^** uu b^**]?

[stem]
++++
{a, ab, a b b, a b b b, ... } uu {epsilon, b, b b, b b b, ... } = {epsilon, a, b, ab, b b, a b b, b b b, ...}
++++

What is the language of stem:[ab^+ uu b^+b]?

[stem]
++++
{ab, a b b, a b b b, ...} uu {b b, b b b, b b b b, ... } = ab^** uu b^** // {a, epsilon, b} " (excluding " a, epsilon, b ")"
++++

What is the language of stem:[Sigma^** a]?

[stem]
++++
{a, aa, ba, aaa, aba, baa, b b a, ...}
++++

What is the language of stem:[Sigma^** a Sigma^**]?

[stem]
++++
{a, aa, ab, ba, aaa, aab, aba, a b b, baa, bab, b b a, ...}
++++
